<?php

/**
 * @file
 * stanford_fields.module
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\field\FieldConfigInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function stanford_fields_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\field\FieldConfigInterface $field_config */
  $field_config = $form_state->get('field_config');
  if ($field_config->getType() == 'link') {
    $form['settings']['force_relative'] = [
      '#type' => 'checkbox',
      '#title' => t('Force relative internal links'),
      '#default_value' => $field_config->getThirdPartySetting('stanford_fields', 'force_relative'),
      '#states' => [
        'invisible' => [
          ':input[name="settings[link_type]"]' => ['value' => '16'],
        ],
      ],
    ];
    $form['#entity_builders'][] = 'stanford_fields_form_field_config_entity_builder';
  }
}

/**
 * Implements hook_field_widget_third_party_settings_form().
 */
function stanford_fields_field_widget_third_party_settings_form(WidgetInterface $plugin, FieldDefinitionInterface $field_definition, $form_mode, array $form, FormStateInterface $form_state) {
  $element = [];
  if ($plugin->getPluginId() == 'fontawesome_icon_widget') {
    $element['hidden_settings'] = [
      '#type' => 'select',
      '#title' => t('My setting'),
      '#default_value' => $plugin->getThirdPartySetting('stanford_fields', 'hidden_settings'),
      '#multiple' => TRUE,
      '#options' => [
        'iconset' => t('Icon Set'),
        'size' => t('Size'),
        'fixed-width' => t('Fixed Width'),
        'border' => t('Border'),
        'invert' => t('Invert Color'),
        'animation' => t('Animation'),
        'pull' => t('Pull'),
        'additional_classes' => t('Additional Classes'),
        'duotone' => t('Duotone Settings'),
        'masking' => t('Icon Mask'),
        'power_transforms' => t('Power Transforms'),
      ],
    ];
  }
  return $element;
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function stanford_fields_field_widget_complete_fontawesome_icon_widget_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  $hidden_settings = $context['widget']->getThirdPartySetting('stanford_fields', 'hidden_settings');
  foreach (Element::children($field_widget_complete_form['widget']) as $delta) {
    foreach ($hidden_settings as $hidden_setting) {
      $field_widget_complete_form['widget'][$delta]['settings'][$hidden_setting]['#access'] = FALSE;
    }
  }
}

/**
 * Field config form submission to save the third party settings.
 *
 * @param string $entity_type
 *   Entity type ID.
 * @param \Drupal\field\FieldConfigInterface $entity
 *   Submitted entity object.
 * @param array $form
 *   Submitted form render array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Submitted form state.
 */
function stanford_fields_form_field_config_entity_builder(string $entity_type, FieldConfigInterface $entity, array &$form, FormStateInterface $form_state) {
  if ($form_state->getValue(['settings', 'force_relative'])) {
    $entity->setThirdPartySetting('stanford_fields', 'force_relative', TRUE);
    return;
  }
  $entity->unsetThirdPartySetting('stanford_fields', 'force_relative');
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function stanford_fields_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  foreach ($fields as $field) {
    if ($field->getType() == 'link' && $field->getThirdPartySetting('stanford_fields', 'force_relative')) {
      $field->addConstraint('relative_internal_link', []);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add validation to field add form.
 */
function stanford_fields_form_field_ui_field_storage_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#validate'][] = 'stanford_fields_field_storage_add_validate';
}

/**
 * Field storage add validation to prevent hashed table names.
 *
 * @see \Drupal\Core\Entity\Sql\DefaultTableMapping::generateFieldTableName()
 */
function stanford_fields_field_storage_add_validate(&$form, FormStateInterface $form_state) {
  $entity_type = $form_state->getBuildInfo()['args'][0];
  $field_name = $form_state->getValue('field_name');
  $field_prefix = \Drupal::config('field_ui.settings')->get('field_prefix');

  // When a table name is over 48 characters, Drupal will hash the field name
  // to create a shorter field table. This makes it nearly impossible to track
  // down exactly what table is for what field without inspecting the field
  // storage config entity.
  if (strlen("{$entity_type}_revision__{$field_prefix}$field_name") > 48) {
    $allowed_length = 48 - strlen("{$entity_type}_revision__{$field_prefix}");
    $form_state->setError($form['new_storage_wrapper']['field_name'], t('Field name is too long. Please keep this field name under @count characters', ['@count' => $allowed_length]));
  }
}

/**
 * Implements hook_cron().
 */
function stanford_fields_cron() {
  \Drupal::service('stanford_fields.field_cache')->invalidateDateFieldsCache();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function stanford_fields_preprocess_oembed_lazyload(&$variables) {
  // Remove the ID attribute because it is not unique on the same page.
  unset($variables['iframe']['#attributes']['id']);
}
