field.widget.settings.datetime_year_only:
  type: mapping
  label: 'Year Only Date widget settings'
  mapping:
    increment:
      type: integer
      label: 'Time increments'
    date_order:
      type: string
      label: 'Date part order'
    time_type:
      type: string
      label: 'Time type'
    start:
      type: integer
      label: 'Start Year'
    end:
      type: integer
      label: 'End Year'
field.widget.settings.localist_url:
  type: mapping
  label: 'Localist URL widget settings'
  mapping:
    base_url:
      type: string
      label: 'Base URL'
    placeholder_url:
      type: string
      label: 'Placeholder URL'
    placeholder_title:
      type: string
      label: 'Placeholder title'
